FROM mysql:8.0.33

COPY ./docker/mysql/config/create_database.sql /docker-entrypoint-initdb.d/create_database.sql
RUN ./docker/mysql/config/set_native_password.sql /docker-entrypoint-initdb.d/set_native_password.sql
COPY ./docker/mysql/config/mysql.cnf /etc/mysql/conf.d/mysql.cnf
